# ndarray의 인덱싱과 슬라이싱

## 행렬 ndarray의 인덱싱과 슬라이싱

In [7]:
a = [[0,1,2], [3,4,5], [5,6,7]]
print(a[0])
print(a[1])
print(a[2], '\n')

print(a[0][0], a[0][1], a[0][2])
print(a[1][0], a[1][1], a[1][2])
print(a[2][0], a[2][1], a[2][2])

[0, 1, 2]
[3, 4, 5]
[5, 6, 7] 

0 1 2
3 4 5
5 6 7


In [12]:
import numpy as np
a = np.arange(12).reshape(3,4) # 3개의 ndarray를 가지고 있다. 
print(a, '\n')

print('a[0] : ', a[0])
print('a[1] : ', a[1])
print('a[2] : ', a[2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

a[0] :  [0 1 2 3]
a[1] :  [4 5 6 7]
a[2] :  [ 8  9 10 11]


In [15]:
a = np.arange(9).reshape(3,3)
print(a, '\n')
print(a[0,0], a[0,1], a[0,2])
print(a[1,0], a[1,1], a[1,2])
print(a[2,0], a[2,1], a[2,2])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

0 1 2
3 4 5
6 7 8


In [17]:
a = np.arange(12).reshape(3,4)  
print(a, '\n')

print(a[0, 1:])
print(a[1, :3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[1 2 3]
[4 5 6]


In [18]:
a = np.arange(12).reshape(3,4)  
print(a, '\n')

print(a[1:, 0])
print(a[:3, 1])
print(a[1:3, 2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[4 8]
[1 5 9]
[ 6 10]


In [25]:
a = np.arange(16).reshape(4,4)
print(a[1:3, 1:3])
print('\n', a[:2, :3])
print('\n',a[1:, 2:])

[[ 5  6]
 [ 9 10]]

 [[0 1 2]
 [4 5 6]]

 [[ 6  7]
 [10 11]
 [14 15]]


In [32]:
image = np.arange(9).reshape(3,3)
horizontal_flip = image[:, ::-1] # 180도 방향으로 뒤집기 (좌우 반전)
print('horizontal_flip')
print(horizontal_flip, '\n')

vertical_flip = image[::-1, :] # 90도 회전
print('vertical_flip')
print(vertical_flip, '\n')

rotation = image[::-1,::-1] # 360도 회전
print('rotation')
print(rotation)

horizontal_flip
[[2 1 0]
 [5 4 3]
 [8 7 6]] 

vertical_flip
[[6 7 8]
 [3 4 5]
 [0 1 2]] 

rotation
[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [37]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a, '\n')
print(a[0, :])
print(a[0, ...]) # 뒤따르는 모든 행렬에 대해 가져오세요. (점은 3개만)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[0 1 2 3]
[0 1 2 3]


## (3차원) 텐서에 대한 인덱싱 & 슬라이싱

In [48]:
a = np.arange(27).reshape(3,3,3)
print(a, '\n')

print('a[0] :\n', a[0])
print('a[1] :\n', a[1])
print('a[2] :\n', a[2])

"""밑에 continued"""

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

a[0] :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a[1] :
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
a[2] :
 [[18 19 20]
 [21 22 23]
 [24 25 26]]


In [51]:
print(a[0,0])
print(a[0,1])
print(a[0,2], '\n')

print(a[1,0])
print(a[1,1])
print(a[1,2], '\n')

print(a[2,0])
print(a[2,1])
print(a[2,2], '\n')

[0 1 2]
[3 4 5]
[6 7 8] 

[ 9 10 11]
[12 13 14]
[15 16 17] 

[18 19 20]
[21 22 23]
[24 25 26] 



In [55]:
# 3차원 이미지에 대하여~
print(a[0, :2, :2])
print(a[1, :2, :])
print(a[2, -2:, -2:])

[[0 1]
 [3 4]]
[[ 9 10 11]
 [12 13 14]]
[[22 23]
 [25 26]]


In [62]:
images = np.random.normal(size=(32,100,200))
print('image set: ', images.shape)
image0 = images[0, :, :]
print(image0.shape)
image0 = images[0, ...]
print(image0.shape)
col0 = images[:, :, 0]
print(col0.shape)
col0 = images[..., 0]
print(col0.shape)
image0_col0 = images[0, :, 0]
print(image0_col0.shape)
image0_col_ = images[0, ..., 0]
print(image0_col0.shape)

image set:  (32, 100, 200)
(100, 200)
(100, 200)
(32, 100)
(32, 100)
(100,)
(100,)


In [74]:
# exercises_01
tensors = np.arange(27).reshape(3,3,3)
print(tensors[:, :2, :])
print('-'*30)
print(tensors[..., :2, :])

# exercises_02
print('#'*30)
print(tensors[:, :, 0].T) # 첫번째 컬럼 모두 가져와라. 
print(tensors[..., 0].T)

print('#'*30)
print(tensors[1:, -2:, -2:]) # 첫번째 채널부터 끝까지 


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
##############################
[[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]
[[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]
##############################
[[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


In [79]:
import numpy as np
image = np.random.normal(size=(3,500,300))
image_r = image[0]
image_g = image[1]
image_b = image[2]

print(image_r.shape, image_g.shape, image_b.shape, '\n')

# tuple unpacking
# why? --> 3개의 값을 가지기 때문에
image_r, image_g, image_b = image
print(image_r.shape)
print(image_g.shape)
print(image_b.shape)

(500, 300) (500, 300) (500, 300) 

(500, 300)
(500, 300)
(500, 300)


In [87]:
image = np.random.normal(size=(3,500,300))
top_left = image[:, :100, :100]
top_right = image[: ,:100, -100:]
bottom_right = image[:, -100:, -100]
bottom_left = image[:, -100:, :100]

print(top_left.shape, top_right.shape)
print(bottom_left.shape, bottom_right.shape)

(3, 100, 100) (3, 100, 100)
(3, 100, 100) (3, 100)


## int ndarray

In [93]:
import numpy as np
a = np.arange(10)
indices = np.array([0,3,4])
a[indices] # 0,3,4만 뽑아오고 싶을 때 (불규칙적인 index를 가져오고 싶을 때)

array([0, 3, 4])

In [94]:
indices = np.array([0,0,5,5])
a[indices] # 중복된 index도 가져올 수 있음. 

array([0, 0, 5, 5])

In [96]:
indices = np.array([[1,2,3], [5,8,9]]) # indices 자체가 (2,3)
a[indices] # 그 이후에 값을 뽑아와서 각각에 넣어줌. 

array([[1, 2, 3],
       [5, 8, 9]])

In [101]:
# 확장
a = np.random.randint(0,20, (10,)) # (10, )
print(a)
indices = np.random.randint(0,10, size=(2,3,4)) #(2, 3, 4)
print(indices)
print('--------------indexing ----------------------------------')
print(a[indices]) (2, 3, 4)

[ 0 13  2 16 19 16 16 12  0  1]
[[[0 5 3 9]
  [6 5 6 8]
  [2 4 1 3]]

 [[7 0 5 1]
  [5 4 6 1]
  [8 1 2 7]]]
--------------indexing ----------------------------------
[[[ 0 16 16  1]
  [16 16 16  0]
  [ 2 19 13 16]]

 [[12  0 16 13]
  [16 19 16 13]
  [ 0 13  2 12]]]


In [106]:
import numpy as np
a = np.arange(12).reshape(3,4) # (3, 4)
print(a, '\n')

print('a[0] : ', a[0])
print('a[1] : ', a[1])
print('a[2] : ', a[2])

print('=============== indexed ==================')
indices = np.array([0,2]) # (2, )
print('indices : ', indices, '\n')
print(a[indices]) # (2, 4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

a[0] :  [0 1 2 3]
a[1] :  [4 5 6 7]
a[2] :  [ 8  9 10 11]
=============== indexed ==================
indices :  [0 2] 

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [107]:
indices = np.array([0,0,1,1,2,2]) # (6, )
a[indices] # (6, 4)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [111]:
a = np.arange(12).reshape(3,4) # (3,4)
indices = np.array([[0,1,2], [-3,-2,-1]]) # (2,3)
print(a, '\n')
print("indices : ")
print(indices)
print('=========== indexed =========')
print(a[indices])
print('shape : ', a[indices].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

indices : 
[[ 0  1  2]
 [-3 -2 -1]]
=========== indexed =========
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
shape :  (2, 3, 4)


In [118]:
a = np.arange(12).reshape(3,4)
print(a, '\n')
indices0, indices1 = np.array([0]), np.array([0])
print(a[indices0, indices1])

indices0, indices1 = np.array([1]), np.array([2]) # 각각이 ndarray 
print(a[indices0, indices1])

indices0, indices1 = np.array([0,1,2]), np.array([1,2,3])
a[indices0, indices1] # 2개의 차원에 대해서 전부다 index를 만듬
                      # row별로가 아니라 실제 스칼라 값에 접근

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[0]
[6]


array([ 1,  6, 11])

In [150]:
indices0 = np.array([[0,1,2], [0,1,2]]) # (2,3)
indices1 = np.array([[0,1,2], [1,2,3]]) # (2,3)
print(indices0)
print(indices1)
a[indices0, indices1]

[[0 1 2]
 [0 1 2]]
[[0 1 2]
 [1 2 3]]


array([[ 0,  5, 10],
       [ 1,  6, 11]])

## boolean ndarray로 인덱싱 하기

In [151]:
a = np.arange(5)
print(a, '\n')

b_indices = np.array([True, False, True, False, True])
a[b_indices] # shape가 같아야지 인덱싱이 가능함. 

[0 1 2 3 4] 



array([0, 2, 4])

In [154]:
a = np.random.randint(0,20, size=(10,))
print(a, '\n')
b_indices = (a%2 == 0) # even numbers
a[b_indices] # 원하는 값들만 뽑아오기 

[12 12 18 15  3  8 16  3  6 14] 



array([12, 12, 18,  8, 16,  6, 14])

In [156]:
# 행렬인 경우
matrix = np.random.randint(0,20, (2,2))
b_indices = np.array([[True, False],
                      [False, True]])
print(matrix[b_indices]) # 결과가 matrix ==> vector로 나옴. 

[13 11]


In [158]:
a = np.random.randint(0,20, (3,4))
b_indices = (a > 10) # boolean indexing
a[b_indices] # True인 값들만 뽑아오기 
"""결국엔 판다스에서 boolean indexing해오는 것과 동일함. 다른게 없음. """

array([14, 11, 16, 19])

In [163]:
a = np.array([True, False, True, False])
nonzero = np.nonzero(a)
where = np.where(a)
print(a)
print(nonzero) # 0이 아닌 부분의 인덱스를 가져옴.
print(where)

[ True False  True False]
(array([0, 2]),)
(array([0, 2]),)


In [166]:
a = np.array([[True, False],
              [True, False]])
nonzero = np.nonzero(a)
where = np.where(a)
print(a)
print(nonzero) # integer ndarray 값을 돌려줌. 
print(where)

[[ True False]
 [ True False]]
(array([0, 1]), array([0, 0]))
(array([0, 1]), array([0, 0]))


In [174]:
a = np.array([[[True, False, True],
               [True, False, False],
              
               [False, True, False],
               [True, False, True]]])
nonzero = np.nonzero(a)
where = np.where(a)
print(nonzero)
print(where) """integer인덱스를 돌려주는 구나! """

(array([0, 0, 0, 0, 0, 0]), array([0, 0, 1, 2, 3, 3]), array([0, 2, 0, 1, 0, 2]))
(array([0, 0, 0, 0, 0, 0]), array([0, 0, 1, 2, 3, 3]), array([0, 2, 0, 1, 0, 2]))


In [175]:
a = np.random.randint(-2,3, size=(3,3))

u_nonzero = a[np.nonzero(a)]
u_where = a[np.where(a)]
u_bool = a[a != 0] 

print(u_nonzero) # 인덱스를 뽑아줌.  
print(u_where)
print(u_bool)

[ 1 -2 -1  1 -2 -1  1  2]
[ 1 -2 -1  1 -2 -1  1  2]
[ 1 -2 -1  1 -2 -1  1  2]


In [179]:
a = np.random.randint(-2,3,size=(3,3))
print(a)
u_nonzero = a[np.nonzero(a > 0)] # 양수인 것들의 인덱스만 가져와서~ 
u_where = a[np.where(a > 0)]
u_bool = a[a>0]

print(u_nonzero)
print(u_where)
print(u_bool)

[[ 0  2  1]
 [-2  0  1]
 [ 0  0  0]]
[2 1 1]
[2 1 1]
[2 1 1]


# API들의 axis, keepdims 인자

## 행렬 ndarray에서의 axis, keepdims

In [ ]:
# np.sum 
# np.cumsum
# np.prod
# np.cumprod
# np.diff
# np.mean
# np.median
# np.var
# np.std
# np.amax
# np.argmax
# np.amin
# np.argmin
# np.sort

In [183]:
# np.sum
a = np.arange(5)
print(a, '\n')
print(np.sum(a))

b = np.arange(6).reshape(2,-1)
print(b)
print('b sum : ', b.sum())

[0 1 2 3 4] 

10
[[0 1 2]
 [3 4 5]]
b sum :  15


In [186]:
a = np.arange(12).reshape(3,-1)
print(a)
print('sum of all numbers : ', a.sum())
print('sum of axis 0 : ', a.sum(axis=0)) 
print('sum of axis 1 : ', a.sum(axis=1))

"""
a.shape ==> (3,4)
axis=0을 기준으로 더할 시에는 (3,)이 사라지고 합은 (4,) 형태로 변함
axis=1을 기준으로 더할 시에는 (,4)는 사라지고 합은 (3,) 형태로 변함 
"""

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum of all numbers :  66
sum of axis 0 :  [12 15 18 21]
sum of axis 1 :  [ 6 22 38]


In [193]:
a = np.arange(12).reshape(3,-1) # (3,4)
sum_class = np.sum(a, axis=0)
sum_student = np.sum(a, axis=1)
print(sum_class.shape)
print(sum_student.shape)

(4,)
(3,)


In [194]:
# dimension을 떨어뜨리고 싶지 않을 때
a = np.arange(12).reshape(3,-1)

sum_class = np.sum(a, axis=0, keepdims=True)
sum_student = np.sum(a, axis=1, keepdims=True)

print(sum_class.shape)
print(sum_student.shape)

(1, 4)
(3, 1)


In [201]:
import numpy as np
n_student, n_class = 3,4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score, high=M_score,
                           size=(n_student, n_class))
mean_class = np.mean(scores, axis=0, keepdims=True)
mean_class_x_kd = np.mean(scores, axis=0, keepdims=False)
mean_student = np.mean(scores, axis=1, keepdims=True)
mean_student_x_kd = np.mean(scores, axis=1, keepdims=False)
print(scores.shape, mean_class.shape, mean_student.shape, '\n')
print(scores)
print(scores - mean_class)
print(scores - mean_class_x_kd) # 얘는 broadcasting o (4, )
print(scores - mean_student)
print(scores - mean_student_x_kd) # 오류 발생 ==> broadcast x

(3, 4) (1, 4) (3, 1) 

[[42 27 66 72]
 [31 58 50 18]
 [80 64  6 71]]
[[ -9.         -22.66666667  25.33333333  18.33333333]
 [-20.           8.33333333   9.33333333 -35.66666667]
 [ 29.          14.33333333 -34.66666667  17.33333333]]
[[ -9.         -22.66666667  25.33333333  18.33333333]
 [-20.           8.33333333   9.33333333 -35.66666667]
 [ 29.          14.33333333 -34.66666667  17.33333333]]
[[ -9.75 -24.75  14.25  20.25]
 [ -8.25  18.75  10.75 -21.25]
 [ 24.75   8.75 -49.25  15.75]]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

## 텐서 ndarray에서의 axis, keepdims

In [212]:
# 3rd Order Tensor Case

In [217]:
tensor = np.arange(24).reshape(2,3,4)
print(tensor.sum(axis=0)) # ==> (3,4)
print(tensor.sum(axis=1)) # ==> (2,4)
print(tensor.sum(axis=2)) # ==> (2,3)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


In [218]:
tensor = np.arange(2*3*4).reshape(2,3,4)
sum_ = tensor.sum(axis=1)
sum_k = tensor.sum(axis=1, keepdims=True)
print(sum_.shape, sum_k.shape)

(2, 4) (2, 1, 4)


In [219]:
tensor = np.arange(2*3*4).reshape(2,3,4)
sum_ = tensor.sum(axis=2)
sum_k = tensor.sum(axis=2, keepdims=True)
print(sum_.shape, sum_k.shape)

(2, 3) (2, 3, 1)


In [221]:
# application
n_test_time, n_student, n_class = 4,3,4 # 3명의 학생, 4개의 교과목, 4번의 테스트
m_score, M_score = 0,100
scores = np.random.randint(low=m_score, high=M_score,
                           size=(n_test_time, n_student, n_class))
print("scores: \n", scores)

scores: 
 [[[31 62 92 85]
  [92 80  5 89]
  [62 60 41 84]]

 [[98 73 47 47]
  [41 62 58 56]
  [ 7 23 73 28]]

 [[51 44 94  4]
  [90 22 70 56]
  [26  3 90 64]]

 [[75 82 62 72]
  [16 63 20 54]
  [98 10 84 20]]]


In [224]:
print(scores.mean(axis=0)) # 각 학생이 각 과목에 대하여 받은 점수의 평균
print(scores.mean(axis=1)) # 각 시험의 각 과목당 점수의 평균
print(scores.mean(axis=2)) # 각 시험별 각 학생의 점수 평균 
"""각 값들이 무엇을 의미하는지 정확히 알 필요가 있음"""

[[63.75 65.25 73.75 52.  ]
 [59.75 56.75 38.25 63.75]
 [48.25 24.   72.   49.  ]]
[[61.66666667 67.33333333 46.         86.        ]
 [48.66666667 52.66666667 59.33333333 43.66666667]
 [55.66666667 23.         84.66666667 41.33333333]
 [63.         51.66666667 55.33333333 48.66666667]]
[[67.5  66.5  61.75]
 [66.25 54.25 32.75]
 [48.25 59.5  45.75]
 [72.75 38.25 53.  ]]


In [226]:
# Application_02
C, H, W = 3, 100, 200
images = np.random.randint(0, 256, size=(C, H, W))
print("Shape of original image: ", images.shape)
gray_image = np.mean(images, axis=0) 
print(gray_image.shape)

Shape of original image:  (3, 100, 200)
(100, 200)
