# Calculations of Vectors

## making unit vectors

In [11]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

# generate test vectors
n_element = 4
u = np.random.uniform(0,10,(n_element,))
v = np.random.uniform(0,10,(n_element,))
print('u : ', u)
print('v : ', v, '\n')

# calcuate and print the norms
u_len = np.sqrt(np.sum(np.square(u)))
v_len = np.sqrt(np.sum(np.square(v)))

print(colored('Before unitization', 'green'))
print('len of u : ', u_len.round(2))
print('len of v : ', v_len.round(2))

# unitize the vectors
u_unit = u/u_len
v_unit = v/v_len

# calcuate and print the norms
u_len = np.sqrt(np.sum(np.square(u_unit)))
v_len = np.sqrt(np.sum(np.square(v_unit)))

print(colored('After unitization', 'red'))
print('len of u : ', u_len.round(2))
print('len of v : ', v_len.round(2))

u :  [9.55 4.24 4.07 2.28]
v :  [6.11e+00 4.63e+00 5.83e-03 7.82e+00] 

Before unitization
len of u :  11.44
len of v :  10.95
After unitization
len of u :  1.0
len of v :  1.0


## making unit vectors(matrix)

In [22]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element = 3,4
U = np.random.uniform(0,10,(n_vector, n_element))
print(U, '\n')

# calculate and print the norm
U_len = np.sqrt(np.sum(np.square(U), axis=1)).reshape(-1,1) # column_vector로 만들기
print(colored('Before unitization', 'green'))
print('len of U :\n', U_len, '\n')

# unitize the vectors
U_unit = U/U_len

U_len = np.sqrt(np.sum(np.square(U_unit), axis=1)).reshape(-1,1) 
print(colored('Before unitization', 'red'))
print('len of U :\n', U_len)

[[3.29 0.98 0.02 9.16]
 [5.94 3.25 1.09 1.37]
 [1.57 3.98 3.37 9.58]] 

Before unitization
len of U :
 [[ 9.79]
 [ 7.  ]
 [11.02]] 

Before unitization
len of U :
 [[1.]
 [1.]
 [1.]]


## Euclidean Distances

In [28]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_element=4
u = np.random.uniform(0,10,(n_element,)).astype(np.float32)
v = np.random.uniform(0,10,(n_element,)).astype(np.float32)
print('u shape : ', u.shape, 'u : ', u)
print('v shape : ', v.shape, 'v : ', v)

# calcuate and print the Euclidean distance
e_dist = np.sqrt(np.sum(np.square(u - v)))
print('Euclidean distance : ', e_dist.round(3))

u shape :  (4,) u :  [5.26 3.11 1.38 9.38]
v shape :  (4,) v :  [2.64 2.08 0.91 3.1 ]
Euclidean distance :  6.893


***Euclidean Distances(vector-wise)***

In [36]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element= 3, 4
U = np.random.uniform(0,10,(n_vector, n_element)).astype(np.float32)
V = np.random.uniform(0,10,(n_vector, n_element)).astype(np.float32)
print('u shape : ', u.shape, '\n', u)
print('v shape : ', v.shape, '\n',  v)

# calculate and print the Euclidean distances
e_dist = np.sqrt(np.sum(np.square(U - V)))
print(e_dist)

u shape :  (3, 4) 
 [[7.67 8.07 2.42 1.3 ]
 [7.03 2.73 0.55 2.4 ]
 [5.2  6.8  3.36 2.53]]
v shape :  (3, 4) 
 [[4.79 5.43 7.25 0.5 ]
 [4.2  9.84 0.26 2.07]
 [3.56 1.59 4.53 7.69]]
13.208297


***Euclidean Distances(Fully-connected)***

In [69]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector1, n_vector2 = 3,4
n_element = 4
U = np.random.uniform(0,10,(n_vector1, n_element)).astype(np.float32)
V = np.random.uniform(0,10,(n_vector2, n_element)).astype(np.float32)
print('u shape : ', U.shape, '\n', U)
print('v shape : ', V.shape, '\n',  V)

U_ = np.expand_dims(U, axis=0)
V_ = np.expand_dims(V, axis=1)
print(U_.shape, V_.shape)

# e_dists1
e_dists1 = np.square(U_ - V_)
e_dists1 = np.sqrt(np.sum(np.square(U_ - V_), axis=-1))

print('\n', e_dists1.shape)


# e_dists2

U_ = np.expand_dims(U, axis=1)
V_ = np.expand_dims(V, axis=0)
print(U_.shape, V_.shape)

e_dists2 = np.square(U_ - V_)
e_dists2 = np.sqrt(np.sum(np.square(U_ - V_), axis=-1))
print(e_dists2.T.shape)

print(colored('\nAre two vectors same?', 'red'))
print(e_dists1 == e_dists2.T)



u shape :  (3, 4) 
 [[5.07 4.95 0.17 7.08]
 [2.67 9.3  1.77 1.45]
 [9.54 5.76 2.72 6.02]]
v shape :  (4, 4) 
 [[0.57 7.63 1.26 6.58]
 [1.8  3.17 3.26 7.58]
 [2.63 5.29 8.83 8.78]
 [1.21 9.63 1.3  5.5 ]]
(1, 3, 4) (4, 1, 4)

 (4, 3)
(3, 1, 4) (1, 4, 4)
(4, 3)

Are two vectors same?
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Manhattan Distance

In [113]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_element=4
u = np.random.uniform(0,10,(n_element,)).astype(np.float32)
v = np.random.uniform(0,10,(n_element,)).astype(np.float32)
print('u shape : ', u.shape, 'u : ', u)
print('v shape : ', v.shape, 'v : ', v)

# calculate and print the Manhattan distance
m_dists = np.sum(np.abs(u-v))
print(m_dists)

u shape :  (4,) u :  [1.55 9.38 2.74 1.79]
v shape :  (4,) v :  [2.15 1.95 4.4  8.84]
16.73716


## Manhattan Distances(Vector-wise)

In [115]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element=3,4
u = np.random.uniform(0,10,(n_vector, n_element)).astype(np.float32)
v = np.random.uniform(0,10,(n_vector, n_element)).astype(np.float32)
print('u shape : ', u.shape, 'u : ', u)
print('v shape : ', v.shape, 'v : ', v)

# calculate and print the Manhattan distance
m_dists = np.sum(np.abs(u-v))
print(m_dists)

u shape :  (3, 4) u :  [[6.75 1.71 2.66 3.42]
 [1.92 4.32 7.33 8.38]
 [4.28 9.25 5.73 6.09]]
v shape :  (3, 4) v :  [[3.96 6.48 4.39 6.45]
 [9.77 4.59 1.35 6.48]
 [9.26 4.76 9.31 2.21]]
45.230125


## Manhattan Distances(Fully-connected)

In [120]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector1, n_vector2 = 3,4
n_element = 4
U = np.random.uniform(0,10,(n_vector1, n_element)).astype(np.float32)
V = np.random.uniform(0,10,(n_vector2, n_element)).astype(np.float32)
print('u shape : ', U.shape, '\n', U)
print('v shape : ', V.shape, '\n',  V)

U_ = np.expand_dims(U, axis=0)
V_ = np.expand_dims(V, axis=1)
print(U_.shape, V_.shape)

# e_dists1
m_dists1 = np.square(U_ - V_)
m_dists1 = np.sum(np.abs(U_ - V_), axis=-1)

print('-'*65)
print('Manhattan_distance :\n', m_dists1)

u shape :  (3, 4) 
 [[6.7  5.45 7.27 5.14]
 [8.45 6.02 0.68 1.66]
 [8.18 1.65 0.31 0.25]]
v shape :  (4, 4) 
 [[9.84 7.97 6.3  5.45]
 [3.32 2.89 9.79 7.11]
 [3.91 5.1  9.82 1.45]
 [8.28 9.75 0.09 8.62]]
(1, 3, 4) (4, 1, 4)
-----------------------------------------------------------------
Manhattan_distance :
 [[ 6.95 12.76 19.17]
 [10.43 22.82 22.43]
 [ 9.38 14.81 18.41]
 [16.55 11.44 16.8 ]]


## Cosine Similarity

In [135]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

# generate test vectors
n_element = 4
# u = np.random.uniform(0,10,(n_element,))
# v = np.random.uniform(0,10,(n_element,))
u = np.array([0,1])
v = np.array([1,0])

print('u : ', u)
print('v : ', v, '\n')

# unitize the vectors
u_len = np.sqrt(np.sum(np.square(u)))
u_unit = u/u_len
v_len = np.sqrt(np.sum(np.square(v)))
v_unit = v/v_len

# dot product
cos = np.sum(u_unit * v_unit)
print('cos value : ', cos) # 비슷한 방향으로 가고 있음. 


u :  [0 1]
v :  [1 0] 

cos value :  0.0


## cosine similaries(vector-wise)

In [193]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element= 3, 4
U = np.random.uniform(0,10,(n_vector, n_element))
V = np.random.uniform(0,10,(n_vector, n_element))

# calculate and print the Manhattan distance
U_norms = np.sqrt(np.sum(np.square(U), axis=1)).reshape((-1,1)) # vector들 마다로 해주기 위해 axis=1
U_unit = U/U_norms
V_norms = np.sqrt(np.sum(np.square(V), axis=1)).reshape((-1,1))
V_unit = U/V_norms

# calculate cos similarities
sims = np.sum(U_unit * V_unit, axis=1)
print(sims)


[0.72 1.1  1.64]


## cosine simliarities (fully-connected)

In [201]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector1, n_vector2 = 3,4
n_element = 4
U = np.random.uniform(0,10,(n_vector1, n_element)).astype(np.float32)
V = np.random.uniform(0,10,(n_vector2, n_element)).astype(np.float32)

# calculate and print the Manhattan distance
U_norms = np.sqrt(np.sum(np.square(U), axis=1)).reshape((-1,1)) # vector들 마다로 해주기 위해 axis=1
U_unit = U/U_norms
V_norms = np.sqrt(np.sum(np.square(V), axis=1)).reshape((-1,1))
V_unit = V/V_norms


U_ = np.expand_dims(U_unit, axis=0)
V_ = np.expand_dims(V_unit, axis=1)

print(U_.shape, V_.shape)

sims = np.sum(U_*V_, axis=-1)
sims # V1 벡터와 제일 비슷한 것은 U1 

(1, 3, 4) (4, 1, 4)


array([[0.89, 0.82, 0.72],
       [0.62, 0.85, 0.95],
       [0.67, 0.72, 0.8 ],
       [0.57, 0.57, 0.85]], dtype=float32)

In [230]:
!git init
!git add .
!git commit -m "0413 np exercise part 2 added"
!git push origin master

Reinitialized existing Git repository in /Users/wonbinchoi/current_studying/for_better_np/.git/
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Everything up-to-date
