# Exercise Group.1 Score Calculation

## exercise 1-1 : Data Generation

In [12]:
import numpy as np
np.set_printoptions(precision=2) # .round(2)를 안해주어도 됨.

In [33]:
n_student, n_class = 500, 5
means = np.random.randint(40,60,(n_class,))
stds = np.random.uniform(5,10,(n_class,))

# generate data
scores = np.random.normal(loc=means, scale=stds, size=(n_student, n_class))

# print the setted scores params
print("means : ", means, 'shape : ', means.shape)
print("stds : ", stds, 'shape : ', stds.shape)
print('-'*65)

# print the calculated scores params
print('mean : ', scores.mean(axis=0).shape)
print('std : ', scores.std(axis=0))
print('max : ', scores.max(axis=0))
print('min : ', scores.min(axis=0))

# 학생별
print('-'*65)
print('mean : ', scores.mean(axis=1).shape)
# print('std : ', scores.std(axis=1))
# print('max : ', scores.max(axis=1))
# print('min : ', scores.min(axis=1))

means :  [41 42 43 41 49] shape :  (5,)
stds :  [6.75 6.56 5.56 7.37 5.84] shape :  (5,)
-----------------------------------------------------------------
mean :  (5,)
std :  [6.35 6.6  5.55 7.47 5.92]
max :  [57.6  61.27 61.45 62.08 69.91]
min :  [24.06 24.98 27.69 21.94 31.08]
-----------------------------------------------------------------
mean :  (500,)


## Min-Max Normalization

In [35]:
import numpy as np
def get_scores():
    n_student, n_class = 500, 5
    means = np.random.randint(40,60,(n_class,))
    stds = np.random.uniform(5,10,(n_class,))
    scores = np.random.normal(loc=means, scale=stds, size=(n_student, n_class))
    return scores 

In [50]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

scores = get_scores()

M_scores = scores.max(axis=0)
m_scores = scores.min(axis=0)

print(colored('Before m-M normalization', 'green'))
print(M_scores)
print(m_scores)
print('-'*65)
# min-Max normalization
print(scores.shape) # broadcasting 가능
print(M_scores.shape)
print(m_scores.shape)

scores = (scores - m_scores) / (M_scores - m_scores)
print(scores.shape)
print('-'*65)

print(colored('After m-M normalization', 'red'))
M_scores = scores.max(axis=0)
m_scores = scores.min(axis=0)
print('max scores',M_scores)
print('min_scores', m_scores)

Before m-M normalization
[71.44 81.29 77.06 70.3  71.27]
[30.06 37.28 36.89 19.39 25.1 ]
-----------------------------------------------------------------
(500, 5)
(5,)
(5,)
(500, 5)
-----------------------------------------------------------------
After m-M normalization
max scores [1. 1. 1. 1. 1.]
min_scores [0. 0. 0. 0. 0.]


## standard deviation

In [54]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)
scores = get_scores()
print(scores.shape, '\n')
# calculate the vars, stds with element-wise operations
vars_ = (scores**2).mean(axis=0) - (scores.mean(axis=0)**2)
stds = vars_**0.5
print(vars_)
print(stds, '\n')

# calculate the vars, stds with APIs
vars_ = scores.var(axis=0)
stds = scores.std(axis=0)
print(vars_)
print(stds)


(500, 5) 

[57.66 48.61 53.23 87.02 32.61]
[7.59 6.97 7.3  9.33 5.71] 

[57.66 48.61 53.23 87.02 32.61]
[7.59 6.97 7.3  9.33 5.71]


## 1.4 stadardization

In [67]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)
scores = get_scores()
print('scores shape : ', scores.shape, '\n')

# calculate the means, stds
means = scores.mean(axis=0)
stds = scores.std(axis=0)

# print the means, stds values before standardization
print(colored('Before standardization', 'green'))
print('means : ', means)
print('stds : ', stds, '\n')

# stadardization (using broadcasting)
scores = (scores - means) / stds

# calculate the means, stds
means = scores.mean(axis=0)
stds = scores.std(axis=0)

# print the means, stds values before standardization
print(colored('After standardization', 'red'))
print('means : ', means)
print('stds : ', stds)

scores shape :  (500, 5) 

Before standardization
means :  [48.03 58.79 57.9  45.79 49.65]
stds :  [8.51 5.75 7.03 8.02 5.21] 

After standardization
means :  [ 5.25e-15 -6.37e-15 -2.80e-16 -2.24e-15  5.78e-15]
stds :  [1. 1. 1. 1. 1.]


## Scores to Grades

In [72]:
import numpy as np

# generate data
n_student = 10
scores = np.random.randint(0,100, (n_student,))
print('scores : ', scores, 'scores shape : ', scores.shape, '\n')

cutoffs = np.array([20,40,60,80]).reshape(1,-1)
print('custoffs : ', cutoffs, '/ shape : ', cutoffs.shape)

scores :  [60 96 76 61 42 47 42 75 34 12] scores shape :  (10,) 

custoffs :  [[20 40 60 80]] / shape :  (1, 4)


***for loop 없이***

In [92]:
import warnings
warnings.filterwarnings('ignore')
scores, cutoffs = scores.reshape(-1,1), cutoffs.reshape(1,-1)
print(scores)
print(cutoffs) # broadcasting 가능한 상태
print('-'*65)

grades = (scores > cutoffs).astype(np.int).sum(axis=1)
print(grades)

[[60]
 [96]
 [76]
 [61]
 [42]
 [47]
 [42]
 [75]
 [34]
 [12]]
[[20 40 60 80]]
-----------------------------------------------------------------
[2 4 3 3 2 2 2 3 1 0]


In [100]:
!git init
!git add .
!git commit -m "0413 np exercise added"
!git push origin master

Reinitialized existing Git repository in /Users/wonbinchoi/current_studying/for_better_np/.git/
[master 78d7428] 0413 np exercise added
 6 files changed, 2606 insertions(+), 128 deletions(-)
 create mode 100644 .ipynb_checkpoints/0413_np_exercise_part_01-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/0413_np_exercise_part_02-checkpoint.ipynb
 create mode 100644 0413_np_exercise_part_01.ipynb
 create mode 100644 0413_np_exercise_part_02.ipynb
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 7.88 KiB | 620.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
To https://github.com/owenchoi96/for_better_np.git
   b3250a9..78d7428  master -> master
